---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb
  labels:
    name: dynamodb
    app: dynamodb
spec:
  type: ClusterIP
  selector:
    app: dynamodb
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: http
