---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb
  labels:
    app.kubernetes.io/name: dynamodb
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: dynamodb
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: http
