---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-dynamodb
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: kinesis=docker.io/saidsef/aws-kinesis-local
    argocd-image-updater.argoproj.io/kinesis.force-update: "true"
    argocd-image-updater.argoproj.io/kinesis.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: data
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployment
    repoURL: https://github.com/saidsef/aws-dynamodb-local.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
